### ISSUE TITLE
Error upon clicking

### ISSUE THREAD

**Issue by rmschindler** [dilzeem/hoplon-shadow-cljs#1]
When I click the “click me” button, the text ”you've clicked 0 times” remains unaltered (ie 0 doesn't get incremented), and the following error is seen in the console:
```
browser.cljs:20 shadow-cljs: #3 ready!
core.cljs:44 Uncaught TypeError: Cannot read properties of undefined (reading 'clicks')
    at HTMLButtonElement.eval (core.cljs:44:42)
    at HTMLButtonElement.dispatch (jquery.js:5431:27)
    at HTMLButtonElement.t.handle (jquery.js:5235:28)
eval @ core.cljs:44
dispatch @ jquery.js:5431
t.handle @ jquery.js:5235
```

**Comment by rmschindler** [comment]
I retract the issue. (I was using an `index.html` in which there already was a div with the id `app`, and the line `:id "app"` in the code seems to have conflicted and so caused the above failure.)
